theme: jekyll-theme-cayman
title: Hi! I'm Ruwaa
author: Ruwaa Mohamed
tagline: Hi, I'm Ruwaa Mohamed # blog sub-titile
email: ruwaa.ibrahem@gmail.com # author email

twitter_username: _Ruwaa_
github_username:  ruwaa-mohamed
aboutme: Hi, this is Ruwaa Moahamed. This is my personal page. Pleat take a tour and let me know what do you think of it.
aboutme_photo: https://i1.rgstatic.net/ii/profile.image/822889859264513-1573203639054_Q512/Ruwaa_Mohamed.jpg # your personal photo.
